### ISSUE TITLE
Update package.json and favicon

### ISSUE THREAD

**Issue by petrvecera** [cohstats/coh2stats#203]
- I would like to update favicon on http://coh2stats.com/ to the new logo
- We could add the logo also on the left side - but I am not sure how it will look ? maybe not? ?
![image](https://user-images.githubusercontent.com/8086995/162470823-959918d2-de33-4bb4-af2b-e1259468c663.png)
- Update package.json with new version - ready for the release
- Add this link to the discord server https://discord.gg/jRrnwqMfkr  to the about on the site (it never expires)

**Comment by petrvecera** [comment]
@JohannesMerkt  these are things I want to do before release I can make them later in the evening today, but if you have time feel free to do them too. I am not sure about the logo, maybe that's not important.

**Comment by JohannesMerkt** [comment]
@petrvecera i will start working on the icon and the discord link

**Comment by JohannesMerkt** [comment]
In https://github.com/cohstats/coh2stats/tree/1.3.4-release i have added the new logo and the discord links
