### ISSUE TITLE
Option to show more players' stats on dashboard

### ISSUE THREAD

**Issue by RintFosk** [cohstats/coh2stats#238]
Often There is no rank nor team rank and level stats for the players showing on the dashboard, as player possibly plays exclusively arranged team and/or come back playing the game after a long time, causing their stat to be reset. On this occasion, the dashboard's current stats are insufficient to give valuable insights into players' in-game skill levels and experience.

e.g.
![image](https://user-images.githubusercontent.com/27263945/182963113-b2450d11-eac0-4e5f-8f2d-d0641c1207da.png)

I personally would then go click into each player's personal stat page who has "null-stat" to check following stats:

![image](https://user-images.githubusercontent.com/27263945/182902760-063c6a64-3311-4dac-8542-b7fe17e638bb.png)

which are:
- Current best rank
- Most played mode
- Ranked games played
- Ranked win rate

These stats are not as volatile as rank (and subsequently calculated level) stats, which personally I think are more suitable stats to be shown in the dashboard. The problem with manually opening multiple players' stat pages (while the game is loading) is that it is a bit inconvenient and inefficient. 

If there is an option to show these extensive stats on the dashboard it would be really great.

**Comment by MatejDurech** [comment]
hello i would like to be assigned for this project .

**Comment by petrvecera** [comment]
Hi @MatejDurech  this tasks might be more complicated. I am not sure how well it's documented. 
Some readme is here https://github.com/cohstats/coh2stats/tree/master/packages/app#development

It's in package app . It's an Electron desktop app. 

The idea would be to use expandable row of table 
https://ant.design/components/table/#components-table-demo-expand

Please let me know if you need any assistance here or in our discord.

**Comment by petrvecera** [comment]
https://discord.gg/jRrnwqMfkr

**Comment by MatejDurech** [comment]
i contacted you via Discord.

**Comment by petrvecera** [comment]
Released in desktop app 1.5.0
