### ISSUE TITLE
Permission for CoH2 Replay Analyzer Discord bot to use coh2stats.com as playercard URLs

### ISSUE THREAD

**Issue by Janne252** [cohstats/coh2stats#244]
Hey, due to the official ladders hosted by the Relic Entertainment having been taken offline several months ago, the replay info embeds created by the https://github.com/Janne252/coh2-replay-discord-bot point to invalid playercard URLs. 

![image](https://user-images.githubusercontent.com/4705573/185558175-a91a4204-2209-4f2e-9ba8-e30b4cd302de.png)

Would it be okay for the bot to use `coh2stats.com/players/{steamid}` as the playercard link?
If so, would you prefer a URL parameter to mark the source of origin, e.g. `?utm_source=coh2replaybot`?

**Comment by petrvecera** [comment]
Hi sure, no problem! I think you can point to the site as much as you can :) 

That source would be welcomed addition :) Or you could ad referrer header https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer

I am not sure if it's automatically added or not from discord

**Comment by Janne252** [comment]
Thanks! I won't be able to set headers. I assume Discord redirects all URLs but I haven't inspected what headers Discord sets.

**Comment by Janne252** [comment]
Deployed.
