### ISSUE TITLE
Hacktoberfest: Create a new card with Top post from Reddit

### ISSUE THREAD

**Issue by petrvecera** [cohstats/coh2stats#254]
Difficulty: Medium
Getting started steps: https://github.com/cohstats/coh2stats#development

Create a new "card" component which will display the top 10 post from Reddit from the past week. It should look like https://aoe4world.com/ 
<img width="584" alt="image" src="https://user-images.githubusercontent.com/8086995/192154405-86cb9647-4f29-4923-a38c-22ca8be79b5b.png">

Would be great if we could display - number of upvotes, user, and date. image and obviously the title. It should be clickable to get through. 

Implementation:
You can get the data from reddit with this link `https://www.reddit.com/r/CompanyOfHeroes/top.json?limit=50&t=week` it should not have CORS. We should filter only items which have `link_flair_text= CoH2` it would have great if we could filter that directly in the URL but I didn't find how to do it. Limit it to the top 10 posts. 

Create a new React component under `packages/web/src/components`. The main component should be Card https://ant.design/components/card/ it should accept the props such as width and height. You can test it by adding it to the home packages/web/src/components/main-home.tsx ( but don't commit it added there )  the width would be definitely more that the current cards on the home screne. 

How the component with look like inside is up to you. I would probably recommend using List from Antd
https://ant.design/components/list/#header Icons could be also helpful https://ant.design/docs/spec/icon#header 

Please provide screenshot with the MR. 
Feel free to ask any questions and also if you pick the issue please write into the comments that you are working on it.

**Comment by Malay-dev** [comment]
If no one is already assigned, can I be assigned to this? I am interested.
@petrvecera

**Comment by Malay-dev** [comment]
![test-2](https://user-images.githubusercontent.com/91375797/193057306-8a75a697-9fff-4fa6-aa20-91fadf6af983.png)

Hey, I just wanted to share the progress in making the "Reddit card" does this design seem good enough?

**Comment by petrvecera** [comment]
Looks pretty great! We can try to apply on the info for each text. 
```
    <Text type="secondary">Ant Design (secondary)</Text>
```
![image](https://user-images.githubusercontent.com/8086995/193137289-153c0a9e-72d3-4f8a-8153-7f8bc6b5a8fe.png)

And maybe make the title of each post little bit better but otherwise it looks great! 🎉 

More info for the text styling with Antd is here https://ant.design/components/typography/

**Comment by Malay-dev** [comment]
![test-3](https://user-images.githubusercontent.com/91375797/193410842-72518ffa-1dc7-4830-adec-6e83bc153743.png)
Hey, update - I have used antd - typography to style the info and the title. Is this fine? Shall I start the PR?

**Comment by petrvecera** [comment]
Sure, you can post the PR! 👍

**Comment by Malay-dev** [comment]
Thank you for letting me work on this issue I really enjoyed working on it, do you have any other task I can take up? @petrvecera

**Comment by petrvecera** [comment]
@Malay-dev  thank you for your contribution. Not right now. I have some tasks on my mind but I need to finish some things for them. If I will write up a new task, I will let you know 👍
