### ISSUE TITLE
Hacktoberfest: Add form for editing user 5 fields on user profile 

### ISSUE THREAD

**Issue by petrvecera** [cohstats/coh2stats#256]
Difficulty: Medium (you need to know React) 
Getting started steps: https://github.com/cohstats/coh2stats#development

Add form for editing 5 fields:
- Twitch url
- Youtube url
- Reddit url
- coh2.org url
- twitter url

**Implementation:**

On url http://localhost:3000/userProfile there is userProfile page. You can find this component here
https://github.com/cohstats/coh2stats/blob/master/packages/web/src/pages/profile/user-profile.tsx

There is example how to get the data from the DB:
https://github.com/cohstats/coh2stats/blob/master/packages/web/src/pages/profile/user-profile.tsx#L9

And also how to save to the DB:
https://github.com/cohstats/coh2stats/blob/master/packages/web/src/pages/profile/user-profile.tsx#L22

You can save full object (you can also save just some of the fields) to the database. The object should look like this:
```
{
  twitchUrl: "...",
  youtubeUrl: "...",
  redditUrl: "...",
  twitterUrl: "...",
  coh2orgUrl: ""
}
```
There should be validation. Regex. 
Youtube link should have inside itself "youtube.com" or "youtu.be"
TwitchUrl should have inside itself "twitch.tv"
RedditUrl should have: "reddit.com"
Twitter twitter.com
Coh2org coh2.org

Use Antd forms:
https://ant.design/components/form/

It's completely UP to you how you want to handle STATE and other aspects of the form. If you want to update the DB on each field edit or you want to have "SAVE BUTTON". 
The user page is not yet done, so you work with the mock DB structure. 

If you have any questions feel free to ask.

**Comment by Manthan-Kuber** [comment]
I can take this up. Please assign

**Comment by Manthan-Kuber** [comment]
Hey @petrvecera . If we ran a useEffect to save data to the db if it passes the regex checks, wouldn't that just make unnecessary api calls to the backend? I think the approach of a save button is better and save all of the fields at the same time in just 1 api call.Even if one of the fields are unedited ,  this would just lead to the db overwriting the data record with the same data. What do you think about this ?

**Comment by petrvecera** [comment]
Even more calls to the DB doesn't matter. As these things are not happening very often - people edit their info rarely. 

But one save button is OK too. 👍 

Overwriting the data record with the same data doesn't matter. We are using cloud NoSQL database called Firestore. You pay for write of the whole document. So it really doesn't matter if you overwrite only some parts of it or whole document. In the end for us it's the same.

**Comment by Manthan-Kuber** [comment]
> Even more calls to the DB doesn't matter. As these things are not happening very often - people edit their info rarely.
> 
> But one save button is OK too. 👍
> 
> Overwriting the data record with the same data doesn't matter. We are using cloud NoSQL database called Firestore. You pay for write of the whole document. So it really doesn't matter if you overwrite only some parts of it or whole document. In the end for us it's the same.

Nice👍
I am getting a lot of type errors. I have 'npm i' . Unable to start the work on it

**Comment by petrvecera** [comment]
@Manthan-Kuber  you need to run `yarn install` in the root folder of the project https://github.com/cohstats/coh2stats#development
https://classic.yarnpkg.com/lang/en/docs/install/#windows-stable

than you can run `yarn web start`

**Comment by asi309** [comment]
Please assign this to me.

**Comment by Manthan-Kuber** [comment]
> @Manthan-Kuber you need to run `yarn install` in the root folder of the project https://github.com/cohstats/coh2stats#development https://classic.yarnpkg.com/lang/en/docs/install/#windows-stable
> 
> than you can run `yarn web start`

Yes thanks I installed yarn. I am working on it. Sorry for replying late. Got caught up with exams!
