### ISSUE TITLE
Hacktoberfest: Display empty card when no data are received

### ISSUE THREAD

**Issue by petrvecera** [cohstats/coh2stats#260]
Difficulty: Easy (you know react)
Getting started steps: https://github.com/cohstats/coh2stats#development

We display charts for match analysis on the card. Sometimes there are no specified data. 
Which results in this:
![image](https://user-images.githubusercontent.com/8086995/193403138-ac542b37-bc2a-402e-b58e-6ff82fa6965f.png)

For example on this chart:
https://coh2stats.com/matches/316058123

Your task is to add "EMPTY" icon instead of the chart. 

**Implementation**

There is component ChartCard https://github.com/cohstats/coh2stats/blob/master/packages/web/src/pages/matches/match-details.tsx#L47

This component accepts data array of object. 
If all objects in the array has `value === 0` than we have no data to display. 
And in that case instead of chart the card should have this component:
```
<Empty image={Empty.PRESENTED_IMAGE_SIMPLE} />
```

https://ant.design/components/empty/

Feel free to ask any questions. 
Don't forget to run `yarn fix` before commiting.

**Comment by najeebkp** [comment]
Hi @petrvecera  please assign this to me. i would like to contribute.
