### ISSUE TITLE
Hacktoberfest: Improve the tooltip with more info

### ISSUE THREAD

**Issue by petrvecera** [cohstats/coh2stats#264]
Difficulty: Easy (if you know react) 
Getting started steps: https://github.com/cohstats/coh2stats#development

For the stats https://coh2stats.com/stats?range=month&statsSource=all&type=4v4&race=wermacht&timeStamp=1664582400
Currently the tooltip looks like this
<img width="375" alt="image" src="https://user-images.githubusercontent.com/8086995/193463779-392825b9-b749-4725-af54-c729e347a60c.png">
We need to to add icons of abillities like this
<img width="657" alt="image" src="https://user-images.githubusercontent.com/8086995/193463841-90496d53-3d3c-4d14-a689-96dba3585c55.png">

So the new tooltip should look like this:
<img width="339" alt="image" src="https://user-images.githubusercontent.com/8086995/193465780-fd7e8af8-17bd-4f17-a802-726a0c038ecf.png">
It will be bigger. Have the icons. And then there still will be the text "Click for more info".

**Implementation:**
The tooltip is written here https://github.com/cohstats/coh2stats/blob/master/packages/web/src/components/charts/commanders-bar.tsx#L31

https://github.com/cohstats/coh2stats/blob/master/packages/web/src/pages/commanders/components.tsx#L12
There is already a component which displays the info - maybe we can just utilize this component. Additional styling will be needed to make it look good 👍 

Feel free to ask any questions.

**Comment by indremak** [comment]
Hi, I'd like to work on this issue, could you assign me?

**Comment by petrvecera** [comment]
@indremak  Awesome, thank you for you contribution!
