### ISSUE TITLE
No data displayed

### ISSUE THREAD

**Issue by Cassper17** [cohstats/coh2stats#265]
![image](https://user-images.githubusercontent.com/114881803/193474326-ed54d582-d3c9-4a5d-9d11-b01bbc1611e6.png)
Hi. I do not know why, but I only see this. No data are shown, as highlighted on the pictures here https://coh2stats.com/desktop-app

What am I doing wrong?

**Comment by petrvecera** [comment]
Did you played any game? Try to observe any game from in-game spectating mode. It should display data from that game. 
If it doesn't please check the settings and post the the screenshot of the settings.

**Comment by Cassper17** [comment]
Yes, played two games. One over an hour, one 40+ minutes. ... But weird thing is, that it is not even showing up in the recorded games which I can view as a replay.

I would swear, that last week the program was working. I have installed new PC, just tested how this program worked (previously was using different one for the same purpose) and it showed myself playing vs easy PC or something (when I was still just in main menu and not launching any game).
But then I have connected to the new PC my old HDD with data, and I am not sure if this can be related, but now your program is not showing anything :(

**Comment by petrvecera** [comment]
You need to go to settings and locate the warnings log file. Normally it's in folder:
C:\Users\<user>\Documents\My Games\Company of Heroes 2\warnings.log

But on your computer it might be installed under different user or something

![image](https://user-images.githubusercontent.com/8086995/193688349-2db5a2f5-02da-4037-a84c-24da5da64602.png)

**Comment by Cassper17** [comment]
Perfect, this helped. Thanks a lot !

PS: Snad se uvidíme se u CoH3 :)

**Comment by petrvecera** [comment]
I am glad it helped 👍
