### ISSUE TITLE
Hacktoberfest: Count the amount of downloads of releases from the GitHub API 

### ISSUE THREAD

**Issue by petrvecera** [cohstats/coh2stats#266]
Difficultly: Medium 
Getting started steps: https://github.com/cohstats/coh2stats#development

You need to make a request to the Github API, count the amount of downloads (sum of all versions) and display this number here https://coh2stats.com/desktop-app

<img width="344" alt="image" src="https://user-images.githubusercontent.com/8086995/193474926-270efc60-4af5-4250-a472-af40e83b5955.png">

**Implementation:**

The page component is here https://github.com/cohstats/coh2stats/blob/master/packages/web/src/pages/desktop-app/desktop-app.tsx

Use useEffect to run this request `https://api.github.com/repositories/326416762/releases?page=1&per_page=100` use fetch function from JS to get the data. 

You need to go through all the releases , check if there are some assets ( some might not have), check if there is download count and add all of them together. Aka we want to count all the downloads together. 

<img width="611" alt="image" src="https://user-images.githubusercontent.com/8086995/193475006-e7b7509f-a872-4648-aae4-970d74ffc99f.png">

Feel free to ask if you have any questions.

**Comment by yashdhanore** [comment]
Hey! i'll give this a shot

**Comment by yashdhanore** [comment]
@petrvecera Please have a look

**Comment by petrvecera** [comment]
Thank you for your contribution 👍
