### ISSUE TITLE
Upgrade the menu to the new version AntD

### ISSUE THREAD

**Issue by petrvecera** [cohstats/coh2stats#274]
The top menu of the site:
![image](https://user-images.githubusercontent.com/8086995/194706769-91b44843-40c9-4a06-92c9-2c554174f5aa.png)

Is using components which have breaking changes in new version of AntD
See comments here: https://ant.design/components/menu/#Usage-upgrade-after-4.20.0

TASK: Update it to be compliant with Antd 4.20+, we already have  "antd": "4.22.2", so you can update it. 

The menu is in:
https://github.com/cohstats/coh2stats/blob/master/packages/web/src/components/main-header.tsx#L170

**Comment by indremak** [comment]
Hi, I would like to update this component. Could you assign me?
