### ISSUE TITLE
Player card issue

### ISSUE THREAD

**Issue by kpolan47** [cohstats/coh2stats#289]
CoH 2 Logs & Stats ver. 1.5.0- clicking on player card returns "There was an error loading the player card
"\"Failed to fetch\"""
![2022-11-23](https://user-images.githubusercontent.com/118928515/203619248-d5790d23-147e-46ce-9718-14140f952236.png)

**Comment by petrvecera** [comment]
Thanks for the report. Does it happen with every player? 

As a workaround - in settings switch to open player cards in browser. Thanks

**Comment by kpolan47** [comment]
yes, every player

**Comment by kpolan47** [comment]
also, clicking on Players, Stats, or Map Stats returns a spinning circle

**Comment by JohannesMerkt** [comment]
This must be some sort of connectivity issue

**Comment by petrvecera** [comment]
> This must be some sort of connectivity issue
I recently deployed more advanced protection of the API because of un-authorized use. It's most likely connected to it. But I need to investigate more.

**Comment by petrvecera** [comment]
Fixed in https://github.com/cohstats/coh2stats/releases/tag/v1.5.2
