### ISSUE TITLE
Install and migrate to react-router-dom-v5-compat

### ISSUE THREAD

**Issue by petrvecera** [cohstats/coh2stats#353]
We want to update our web app to react router v6 from v5. 
https://github.com/cohstats/coh2stats/tree/master/packages/web

While the update is annoying. We can migrate by parts by installing https://www.npmjs.com/package/react-router-dom-v5-compat
and we can proceed with the update later.

This is related to the task https://github.com/cohstats/coh2stats/issues/275

**Comment by auan369** [comment]
Hi @petrvecera,

I am interested in taking on this task to kickstart my opensource journey. I have experience working with React and JS on my projects and I am eager to apply this and contribute to this project!

**Comment by petrvecera** [comment]
Awesome, feel free to ask any questions. The goal of the first PR might be
just to swap the router package and make sure that it works. We can
followup later with other conversions .

**Comment by auan369** [comment]
I am having some issues with eslint 

When adding and using the v5-compact module, I'll get this error when running yarn install :
`error Error: EACCES: permission denied, unlink '/Users/lokekumyew/Documents/Projects/opensource/coh2stats/node_modules/@typescript-eslint/experimental-utils/node_modules/@typescript-eslint/visitor-keys/README.md'`


And when launching the local server with yarn start, I'll get this:
`Compiled with warnings.

src/pages/profile/user-profile.tsx
  Line 70:6:  React Hook useEffect has a missing dependency: 'userProfileForm'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

WARNING in src/pages/profile/user-profile.tsx
  Line 70:6:  React Hook useEffect has a missing dependency: 'userProfileForm'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

webpack compiled with 1 warning`

**Comment by auan369** [comment]
This issue only appears when I install compact-v5 (using yarn add), and then try using the module.

I've tried several ways to fix the EACCES: permission denied error, including reinstalling NPM (https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally) and then installing yarn globally using NPM, but the issue persists.

Would you happen to know what could be the cause?

**Comment by auan369** [comment]
Seem to have overcome `error Error: EACCES: permission denied` using `sudo yarn install`.

For the second issue, also seem to have overcome it by adding a <CompatRouter> component

**Comment by petrvecera** [comment]
Nice, you can try creating a Pull Request and I can check the changes 👍

**Comment by auan369** [comment]
Okay! I have submitted the PR with comments on the one part that I have issues with converting to the CompactRoute component

**Comment by petrvecera** [comment]
Fixed by @auan369

**Comment by auan369** [comment]
Currently working on changing all the react-router-dom references to react-router-dom-v5-compat.

I have replaced the Switch components react-router-dom with Routes and have mostly moved the Links to be from react-router-dom-v5-compat. But I'm having issues doing this for Links in main-footer.tsx, main-header.tsx, and main-home.tsx. In my implementation now, loading the commanders of each faction will have errors loading.
Having somr

**Comment by auan369** [comment]
I have solved most of the issues except migrating the Link components from main-footer.tsx and main-header.tsx. Will submit a PR with what I have so far.
